using ProtoBuf;
using System;
using System.IO;
using System.Linq;

namespace BreakProtobufNet.Payload
{
    public class Program
    {
        public static void Main()
        {
            // these bytes that should be generated by Serialize
            var bytes = "0A 05 15 46 41 49 4C".Split(' ').Select(o => Convert.ToByte(o, 16)).ToArray();

            // try to serialize and print output
            using (var ms = new MemoryStream())
            {
                Serializer.Serialize(ms, new ChildType());
                Console.Out.WriteLine(BitConverter.ToString(ms.ToArray()).Replace('-', ' '));
            }

            // try to deserialize and print output
            using (var ms = new MemoryStream(bytes))
            {
                var deserialized = Serializer.Deserialize<ChildType>(ms);
                Console.Out.WriteLine(deserialized.Status);
            }

            // Expected output:
            // 0A 05 15 46 41 49 4C
            // Pass

            // Actual output when run without BreakProtobufNet.Payload.dll in main directory:
            // 15 46 41 49 4C
            // �FAIL
        }
    }
}
